AWSTemplateFormatVersion: '2010-09-09'
Resources:
<<<<<<< HEAD
  NotepadApiFunction:
    Properties:
      CodeUri: s3://notepad-api-deployment/f59dbb7450f9f7c2d36823d9a423007a
=======
  NotesTable:
    Properties:
      PrimaryKey:
        Name: noteId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
  ResourceHandler:
    Properties:
      CodeUri: s3://deployer-build/0d097ed4f346ad199cee8532262caa9a
>>>>>>> c227c83be7088d7aeb27b862877a5bca2f5997fb
      Environment:
        Variables:
          NOTES_TABLE:
            Ref: NotesTable
      Events:
        CreateNote:
          Properties:
            Method: POST
<<<<<<< HEAD
            Path: /notepad/note
=======
            Path: /note
>>>>>>> c227c83be7088d7aeb27b862877a5bca2f5997fb
          Type: Api
        DeleteNote:
          Properties:
            Method: DELETE
<<<<<<< HEAD
            Path: /notepad/note/{noteId}
=======
            Path: /note/{noteId}
>>>>>>> c227c83be7088d7aeb27b862877a5bca2f5997fb
          Type: Api
        GetNote:
          Properties:
            Method: GET
<<<<<<< HEAD
            Path: /notepad/note/{noteId}
=======
            Path: /note/{noteId}
>>>>>>> c227c83be7088d7aeb27b862877a5bca2f5997fb
          Type: Api
        ListNotes:
          Properties:
            Method: GET
<<<<<<< HEAD
            Path: /notepad/notes
=======
            Path: /notes
>>>>>>> c227c83be7088d7aeb27b862877a5bca2f5997fb
          Type: Api
        UpdateNote:
          Properties:
            Method: PUT
<<<<<<< HEAD
            Path: /notepad/note/{noteId}
          Type: Api
      Handler: src/notepadApiRouter.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  NotesTable:
    Properties:
      PrimaryKey:
        Name: noteId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
=======
            Path: /note/{noteId}
          Type: Api
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
>>>>>>> c227c83be7088d7aeb27b862877a5bca2f5997fb
Transform: AWS::Serverless-2016-10-31
