AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  NotesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: noteId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  NotepadApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/router.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          NOTES_TABLE: !Ref NotesTable
      Events:
        # GET /notepad/note/{noteId}
        GetNote:
          Type: Api
          Properties:
            Method: GET
            Path: /notepad/note/{noteId}
        # GET /notepad/notes
        ListNotes:
          Type: Api
          Properties:
            Method: GET
            Path: /notepad/notes
        # POST /notepad/note
        CreateNote:
          Type: Api
          Properties:
            Method: POST
            Path: /notepad/note
        # PUT /notepad/note/{noteId}
        UpdateNote:
          Type: Api
          Properties:
            Method: PUT
            Path: /notepad/note/{noteId}
        # DELETE /notepad/note/{noteId}
        DeleteNote:
          Type: Api
          Properties:
            Method: DELETE
            Path: /notepad/note/{noteId}
